### ISSUE TITLE
Fatal error: spawn ENOENT on Phantom process

### ISSUE THREAD

**Issue by CoderStefan** [henrytao-me/grunt-selenium-webdriver-phantom#1]
Hello,

i will try the way from your example and i came the EONENT error from spawn (child_process) on Windows 7 SP1 Up2Date.
Command:
grunt test:protractor --stack --debug

Errorlog:
Running "selenium_webdriver_phantom:phantom" (selenium_webdriver_phantom) task
[D] Task source: C:\Development\BuildTask
s\node_modules\grunt-selenium-webdriver-phantom\tasks\selenium_webdriver_phantom
.js
Fatal error: spawn ENOENT
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

the source from this error is in selenium_webdriver_phantom.js line 31:
phantomProcess = spawn(options.phantom.path, options.phantom.args);

When i try selenium and phantomjs manual from console then works.

**Comment by CoderStefan** [comment]
my quick and dirty work around:

phantomProcess = spawn('node', [ 'C:/Development/BuildTasks/node_modules/phantomjs/bin/phantomjs', '--webdriver=8080', '--webdriver-selenium-grid-hub=http://127.0.0.1:4444']);
